[versions]
#jetbrains
kotlin = "1.9.10"
#AndroidX
androidx-swiperefreshlayout = "1.1.0"
androidx-documentfile = "1.0.1"
#Fossify
commons = "18ad1dd308"
#Other
autofittextview = "0.2.1"
gestureviews = "2.5.2"
rootshell = "1.6"
roottools = "df729dcb13"
zip4j = "2.11.5"
#Gradle
gradlePlugins-agp = "8.3.0"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "org.fossify.filemanager"
app-version-versionCode = "2"
app-version-versionName = "1.0.1"
[libraries]
#AndroidX
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
#Other
autofittextview = { module = "me.grantland:autofittextview", version.ref = "autofittextview" }
gestureviews = { module = "com.alexvasilkov:gesture-views", version.ref = "gestureviews" }
rootshell = { module = "com.github.Stericson:RootShell", version.ref = "rootshell" }
roottools = { module = "com.github.Stericson:RootTools", version.ref = "roottools" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
